---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creates default user for AWS account
Parameters:
    UserName:
      Type: String
      Description: The username of the user to be created
    Password:
      Type: String
      Description: The password for the user to be created. This should include at least one upper case letter and one number and should be at least 8 characters in length. 
Resources:
  DefaultUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub ${UserName}
      Path : "/"
      LoginProfile: 
        Password: !Sub ${Password}
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonS3FullAccess          
  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !GetAtt 
      - DefaultUser
      - UserName
Outputs:
  DefaultUserArn:
    Value: !GetAtt DefaultUser.Arn
  AccessKeyArn:
    Value: !GetAtt AccessKey.Arn
...
