---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creates default ADMIN user for AWS account
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: "User details"
        Parameters:
          - UserName
    ParameterLabels: 
      UserName: 
        default: "Username"
Parameters:
    UserName:
      Type: String
      Description: The username of the user to be created.
Resources:
  Admin:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: Admin
      ManagedPolicyArns: 
      - arn:aws:iam::aws:policy/AdministratorAccess
  DefaultUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub ${UserName}
      Path : "/"
      Groups: 
        - !Ref Admin
  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref UserName
    DependsOn: DefaultUser
Outputs:
  UserName:
    Value: !Ref UserName
  AccessKey:
    Value: !Ref AccessKey
  SecretKey:
    Value: !GetAtt AccessKey.SecretAccessKey
...
