---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creates default user for AWS account
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: "User details"
        Parameters:
          - UserName
          - Password
    ParameterLabels: 
      UserName: 
        default: "Username"
      Password: 
        default: "Password"
Parameters:
    UserName:
      Type: String
      Description: The username of the user to be created.
    Password:
      Type: String
      Description: The password for the user. This should include at least one upper case letter and one number and should be at least 8 characters in length. 
Resources:
  DefaultUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub ${UserName}
      Path : "/"
      LoginProfile: 
        Password: !Sub ${Password}
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonS3FullAccess    
      - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      - arn:aws:iam::aws:policy/AmazonEC2FullAccess
      - arn:aws:iam::aws:policy/IAMFullAccess
      - arn:aws:iam::aws:policy/AmazonSSMFullAccess
      - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess
      - arn:aws:iam::aws:policy/AWSCodePipeline_FullAccess
      - arn:aws:iam::aws:policy/AWSCodeCommitFullAccess
  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref UserName
Outputs:
  UserName:
    Value: !Ref UserName
  Password:
    Value: !Ref Password
  AccessKey:
    Value: !Ref AccessKey
  SecretKey:
    Value: !GetAtt AccessKey.SecretAccessKey
...
