---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creates default user for AWS account
Parameters:
    UserName:
      Type: String
      Description: The username of the user to be created
    Password:
      Type: String
      Description: The password for the user to be created. This should include at least one upper case letter and one number. 
Resources:
  DefaultUser:
    Type: AWS::IAM::User
    Properties:
      Path : "/"
      LoginProfile: 
        Password: !Sub ${Password}
      UserName: !Sub ${UserName}
Outputs:
  DefaultUserArn:
    Value: !GetAtt DefaultUser.Arn
...
